---

- name: install dependencies
  ansible.builtin.command: /home/{{ installation_os_user }}/actions-runner/bin/installdependencies.sh

- name: configure runner
  ansible.builtin.command: >
    ./config.sh
      --unattended
      --url https://github.com/einfachIT
      --token {{ registration_token }}
  become: true
  become_user: "{{ installation_os_user }}"
  args:
    chdir: /home/{{ installation_os_user }}/actions-runner/

- name: install runner service
  ansible.builtin.command: ./svc.sh install
  args:
    chdir: /home/{{ installation_os_user }}/actions-runner/
  when: false

- name: start runner service
  ansible.builtin.command: ./svc.sh start
  args:
    chdir: /home/{{ installation_os_user }}/actions-runner/
  when: false
