---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: raspios
    image: ${CONTAINER_IMAGE:-"balenalib/raspberrypi4-64-debian-python"}
provisioner:
  name: ansible
verifier:
  name: ansible
