---
- name: Prepare
  hosts: all
  tasks:
    - name: add user group
      user:
        name: 'pi'
        state: present
    - name: add user
      user:
        name: 'pi'
        group: 'pi'
    - name: apt update cache
      apt:
        update_cache: true
